{{- if .Values.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krystalinex.fullname" . }}-basic-auth
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ htpasswd .Values.basicAuth.username .Values.basicAuth.password | b64enc | quote }}
{{- end }}
