{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krystalinex.fullname" . }}-grafana-datasources
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://{{ include "krystalinex.fullname" . }}-prometheus:9090/prometheus
        isDefault: true
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          exemplarTraceIdDestinations:
            - name: traceID
              urlDisplayLabel: "View trace"
              url: '/explore?schemaVersion=1&panes=%7B%22t%22%3A%7B%22datasource%22%3A%22jaeger%22%2C%22queries%22%3A%5B%7B%22query%22%3A%22$${__value.raw}%22%2C%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22jaeger%22%2C%22uid%22%3A%22jaeger%22%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1'
      - name: Jaeger
        type: jaeger
        uid: jaeger
        access: proxy
        url: http://{{ include "krystalinex.fullname" . }}-jaeger:16686/jaeger
        isDefault: false
        jsonData:
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: loki
            filterByTraceID: true
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            lokiSearch: true
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
      {{- if .Values.loki }}
      {{- if .Values.loki.enabled }}
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://{{ include "krystalinex.fullname" . }}-loki:3100
        isDefault: false
        jsonData:
          derivedFields:
            - datasourceUid: jaeger
              matcherRegex: '"traceId"\s*:\s*"(\w+)"'
              name: TraceID
              url: "$${__value.raw}"
            - datasourceUid: jaeger
              matcherRegex: 'traceId=(\w+)'
              name: TraceID
              url: "$${__value.raw}"
      {{- end }}
      {{- end }}
{{- end }}
