{{- if .Values.nodeExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "krystalinex.fullname" . }}-node-exporter
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      {{- include "krystalinex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "krystalinex.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          args:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/host/root'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
            - '--no-collector.arp'
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host/root
              readOnly: true
              mountPropagation: HostToContainer
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krystalinex.fullname" . }}-node-exporter
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9100
      targetPort: metrics
      name: metrics
  selector:
    {{- include "krystalinex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
{{- end }}
