{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krystalinex.fullname" . }}-alertmanager
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "krystalinex.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "krystalinex.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          args:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
            - '--web.external-url=http://localhost:9093/alertmanager/'
          ports:
            - name: http
              containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /alertmanager
          livenessProbe:
            httpGet:
              path: /alertmanager/-/healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /alertmanager/-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "krystalinex.fullname" . }}-alertmanager-config
        - name: data
          {{- if .Values.alertmanager.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "krystalinex.fullname" . }}-alertmanager
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "krystalinex.fullname" . }}-alertmanager
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: http
      name: http
  selector:
    {{- include "krystalinex.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
{{- if .Values.alertmanager.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "krystalinex.fullname" . }}-alertmanager
  labels:
    {{- include "krystalinex.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.alertmanager.persistence.size }}
{{- end }}
{{- end }}
