#!/usr/bin/env node
/**
 * Generate the skill import registry from `src/tools/*.ts`.
 *
 * Existing skills keep their current order to avoid changing listTools()
 * ordering. New skill files are included automatically after the known order,
 * sorted by filename, so adding a backend no longer requires hand-editing the
 * central registry.
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const toolsDir = path.join(repoRoot, 'src', 'tools');
const outFile = path.join(repoRoot, 'src', 'skills.generated.ts');

const KNOWN_ORDER = [
  'traces',
  'metrics',
  'logs',
  'elasticsearch',
  'alertmanager',
  'vmalert',
  'grafana',
  'cilium',
  'kubernetes',
  'clickhouse',
  'pyroscope',
  'opa',
  'envoy',
  'consul',
  'kong',
  'traefik',
  'influxdb',
  'opentsdb',
  'graylog',
  'pinpoint',
  'pipeline',
  'zk-proofs',
  'system',
  'public-exchange',
  'agentrelay',
];

function importName(fileBase: string): string {
  return fileBase.replace(/-([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
}

async function skillFileBases(): Promise<string[]> {
  const entries = await readdir(toolsDir, { withFileTypes: true });
  const candidates = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts'))
    .map((entry) => entry.name.slice(0, -'.ts'.length));

  const skillFiles: string[] = [];
  for (const base of candidates) {
    const content = await readFile(path.join(toolsDir, `${base}.ts`), 'utf8');
    if (/export\s+const\s+skill\b/.test(content)) skillFiles.push(base);
  }
  return skillFiles;
}

function orderedSkillFiles(files: string[]): string[] {
  const known = new Set(KNOWN_ORDER);
  const ordered = KNOWN_ORDER.filter((name) => files.includes(name));
  const appended = files
    .filter((name) => !known.has(name))
    .sort((a, b) => a.localeCompare(b));
  return [...ordered, ...appended];
}

export async function buildSkillRegistrySource(): Promise<string> {
  const files = orderedSkillFiles(await skillFileBases());
  const imports = files.map(
    (file) => `import { skill as ${importName(file)} } from './tools/${file}.js';`,
  );
  const names = files.map(importName);

  return [
    '/**',
    ' * Generated by `npm run gen:skills` from `src/tools/*.ts`.',
    ' * Do not edit by hand.',
    ' */',
    '',
    "import type { Skill } from './skill.js';",
    ...imports,
    '',
    'export const generatedSkills: Skill[] = [',
    ...names.map((name) => `  ${name},`),
    '];',
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const source = await buildSkillRegistrySource();
  await writeFile(outFile, source, 'utf8');
  const count = (source.match(/^  \w+,/gm) ?? []).length;
  process.stdout.write(`Wrote src/skills.generated.ts (${count} skills).\n`);
}

const invokedDirectly =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (invokedDirectly) {
  main().catch((err) => {
    process.stderr.write(`gen-skill-registry failed: ${err?.stack ?? err}\n`);
    process.exit(1);
  });
}
