#!/usr/bin/env node
/**
 * Generate the supported-versions manifest from the typed catalog.
 *
 * Reads `SKILL_VERSIONS` (per-product version tiers + feature since-versions)
 * and `PROTOCOLS` (protocol metadata, baseline & versioned feature summaries),
 * then emits two artifacts grouped by protocol:
 *   - docs/supported-versions.json  (machine-readable, deterministic)
 *   - docs/supported-versions.md    (human-readable tables)
 *
 * The output is deterministic (no timestamps) so a CI drift test can compare a
 * fresh run against the committed files. Run with: `npm run gen:versions`.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { SKILL_VERSIONS } from '../src/skill-versions.js';
import { PROTOCOLS, PROTOCOL_IDS } from '../src/protocols.js';
import type { ProtocolId } from '../src/protocols.js';
import type { BackendVersionSupport } from '../src/versions.js';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const docsDir = path.join(repoRoot, 'docs');

interface BackendEntry {
  skill: string;
  backend: string;
  productVersions: BackendVersionSupport['productVersions'];
  featuresSince: Record<string, string>;
}

interface ProtocolManifest {
  id: string;
  name: string;
  queryLanguage: string;
  products: string[];
  specUrl?: string;
  baselineFeatures: string[];
  versionedFeatures: Record<string, { summary: string; docUrl?: string }>;
  backends: BackendEntry[];
}

function build(): { protocols: ProtocolManifest[] } {
  // Collect backend entries per protocol from the skill data.
  const byProtocol = new Map<ProtocolId, BackendEntry[]>();
  for (const skillId of Object.keys(SKILL_VERSIONS).sort()) {
    const support = SKILL_VERSIONS[skillId];
    for (const backendName of Object.keys(support)) {
      const entry = support[backendName];
      const list = byProtocol.get(entry.protocol) ?? [];
      list.push({
        skill: skillId,
        backend: backendName,
        productVersions: entry.productVersions,
        featuresSince: { ...(entry.protocolFeaturesSince ?? {}) } as Record<string, string>,
      });
      byProtocol.set(entry.protocol, list);
    }
  }

  const protocols: ProtocolManifest[] = [];
  for (const id of PROTOCOL_IDS) {
    const backends = byProtocol.get(id);
    if (!backends || backends.length === 0) continue; // only protocols in use
    const adapter = PROTOCOLS[id];
    protocols.push({
      id,
      name: adapter.name,
      queryLanguage: adapter.queryLanguage,
      products: [...adapter.products],
      specUrl: adapter.specUrl,
      baselineFeatures: [...adapter.baselineFeatures],
      versionedFeatures: adapter.versionedFeatures as Record<
        string,
        { summary: string; docUrl?: string }
      >,
      backends: backends.sort((a, b) => a.backend.localeCompare(b.backend)),
    });
  }
  return { protocols };
}

function tier(t: BackendVersionSupport['productVersions']): string {
  const parts = [`must: ${t.must.join(', ')}`];
  if (t.should?.length) parts.push(`should: ${t.should.join(', ')}`);
  if (t.optional?.length) parts.push(`optional: ${t.optional.join(', ')}`);
  return parts.join(' · ');
}

function renderMarkdown(manifest: { protocols: ProtocolManifest[] }): string {
  const lines: string[] = [];
  lines.push('# Supported Versions');
  lines.push('');
  lines.push(
    '> Generated by `npm run gen:versions` from the typed protocol & version',
  );
  lines.push(
    '> catalog (`src/protocols.ts`, `src/skill-versions.ts`). Do not edit by hand.',
  );
  lines.push('');
  lines.push(
    'Support tiers: **must** = latest major(s) · **should** = previous · **optional** = residual tail.',
  );
  lines.push('');

  for (const p of manifest.protocols) {
    lines.push(`## ${p.name} (\`${p.id}\`)`);
    lines.push('');
    lines.push(`- **Query language:** ${p.queryLanguage}`);
    lines.push(`- **Products:** ${p.products.join(', ')}`);
    if (p.specUrl) lines.push(`- **Spec:** ${p.specUrl}`);
    lines.push('');

    // Product version tiers per configured backend.
    lines.push('### Supported product versions');
    lines.push('');
    lines.push('| Skill | Backend | Tiers |');
    lines.push('| --- | --- | --- |');
    for (const b of p.backends) {
      lines.push(`| \`${b.skill}\` | ${b.backend} | ${tier(b.productVersions)} |`);
    }
    lines.push('');

    if (p.baselineFeatures.length) {
      lines.push('### Baseline features (always available, ungated)');
      lines.push('');
      lines.push(p.baselineFeatures.map((f) => `\`${f}\``).join(', '));
      lines.push('');
    }

    const featureIds = Object.keys(p.versionedFeatures);
    if (featureIds.length) {
      lines.push('### Versioned features — since-version by product');
      lines.push('');
      const header = ['Feature', ...p.backends.map((b) => b.backend)];
      lines.push(`| ${header.join(' | ')} |`);
      lines.push(`| ${header.map(() => '---').join(' | ')} |`);
      for (const fid of featureIds) {
        const summary = p.versionedFeatures[fid]?.summary ?? '';
        const cells = p.backends.map((b) => b.featuresSince[fid] ?? '—');
        lines.push(`| \`${fid}\`<br/><sub>${summary}</sub> | ${cells.join(' | ')} |`);
      }
      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}

async function main() {
  const manifest = build();
  await mkdir(docsDir, { recursive: true });
  const json = JSON.stringify(manifest, null, 2) + '\n';
  await writeFile(path.join(docsDir, 'supported-versions.json'), json, 'utf8');
  await writeFile(
    path.join(docsDir, 'supported-versions.md'),
    renderMarkdown(manifest),
    'utf8',
  );
  process.stdout.write(
    `Wrote docs/supported-versions.json and docs/supported-versions.md ` +
      `(${manifest.protocols.length} protocols).\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`gen-version-manifest failed: ${err?.stack ?? err}\n`);
  process.exit(1);
});
