/**
 * Generated by `npm run gen:skills` from `src/tools/*.ts`.
 * Do not edit by hand.
 */

import type { Skill } from './skill.js';
import { skill as traces } from './tools/traces.js';
import { skill as metrics } from './tools/metrics.js';
import { skill as logs } from './tools/logs.js';
import { skill as elasticsearch } from './tools/elasticsearch.js';
import { skill as alertmanager } from './tools/alertmanager.js';
import { skill as vmalert } from './tools/vmalert.js';
import { skill as grafana } from './tools/grafana.js';
import { skill as cilium } from './tools/cilium.js';
import { skill as kubernetes } from './tools/kubernetes.js';
import { skill as clickhouse } from './tools/clickhouse.js';
import { skill as pyroscope } from './tools/pyroscope.js';
import { skill as opa } from './tools/opa.js';
import { skill as envoy } from './tools/envoy.js';
import { skill as consul } from './tools/consul.js';
import { skill as kong } from './tools/kong.js';
import { skill as traefik } from './tools/traefik.js';
import { skill as influxdb } from './tools/influxdb.js';
import { skill as opentsdb } from './tools/opentsdb.js';
import { skill as graylog } from './tools/graylog.js';
import { skill as pinpoint } from './tools/pinpoint.js';
import { skill as pipeline } from './tools/pipeline.js';
import { skill as zkProofs } from './tools/zk-proofs.js';
import { skill as system } from './tools/system.js';
import { skill as publicExchange } from './tools/public-exchange.js';
import { skill as agentrelay } from './tools/agentrelay.js';
import { skill as beyla } from './tools/beyla.js';

export const generatedSkills: Skill[] = [
  traces,
  metrics,
  logs,
  elasticsearch,
  alertmanager,
  vmalert,
  grafana,
  cilium,
  kubernetes,
  clickhouse,
  pyroscope,
  opa,
  envoy,
  consul,
  kong,
  traefik,
  influxdb,
  opentsdb,
  graylog,
  pinpoint,
  pipeline,
  zkProofs,
  system,
  publicExchange,
  agentrelay,
  beyla,
];
